---
title: "EDA of Home Loan Approvals"
author: "Emily Chen, Kashish Garg, Christian Manaog"
date: "2/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

project_theme  <- theme(axis.text = element_text(size = 8, 
                                                   color = "azure4"),
                          axis.title = element_text(color = "dimgrey"),
                          plot.title = element_text(size = 14),
                          plot.caption = element_text(face = "italic",
                                                      hjust = 0.5), 
                          legend.title = element_text(size = 11),
                          text = element_text(size = 10,
                                              color = "black",
                                              family = "serif"),
                          panel.background = element_rect(fill = "ghostwhite"))
```

# Data Cleaning

We will delete rows that do not have any information about race. This should be okay because there are approximately 1.3 million rows of empty race information, and we will still have ~8.7 million rows.

We will drop ethnicity as well since this is encaptured by race. 

## Removing NAs


```{r data clean, eval= FALSE}
hmda <- read_csv("hmda_lar.csv", n_max = 1000)

na_str <- "Information not provided by applicant in mail, Internet, or telephone application"
# Remove NA/not provided rows
new_hmda <- hmda %>% subset(!(applicant_race_name_1 %in% c(na_str, "Not applicable")))

# NAs
apply(is.na(new_hmda), 2, function(x) sum(x) /nrow(new_hmda))

# Removing bad columns (> 99% na)
new_hmda <-new_hmda %>% select(-respondent_id, -edit_status_name, -co_applicant_race_name_3,
                               -application_date_indicator, -applicant_race_name_4, -co_applicant_race_name_5,
                               -co_applicant_race_name_2, -applicant_race_name_3, -co_applicant_race_name_4,
                               -applicant_race_name_5, -applicant_race_name_2)

# Removing na_str from dataframe
new_hmda <- new_hmda %>% subset(!(applicant_ethnicity_name %in% c(na_str, "Not applicable")))
new_hmda <- new_hmda %>% subset(!(applicant_sex_name %in% c(na_str)))
new_hmda <- new_hmda %>% subset(!(co_applicant_race_name_1 %in% c(na_str)))
new_hmda <- new_hmda %>% subset(!(co_applicant_sex_name %in% c(na_str)))

# Only run if you want to save cleaned file
write.csv(new_hmda, file = "hmda_cleaned.csv")
#new_hmda %>% select(action_taken_name) %>% 
```


```{r}
library(GGally)
loan <- read_csv("hmda_cleaned.csv")

# Remove X1 artifact
loan %>% select(action_taken_name) %>% unique
loan %>% group_by(action_taken_name) %>% summarize(count = n())
loan <- loan %>% select(-X1)
loan <- loan %>% mutate(
  tract_to_msamd_income = as.double(tract_to_msamd_income), 
  rate_spread = as.double(rate_spread),
  population = as.double(population),
  minority_population = as.double(minority_population),
  number_of_owner_occupied_units = as.double(number_of_owner_occupied_units),
  number_of_1_to_4_family_units = as.double(number_of_1_to_4_family_units),
  approved = ifelse(action_taken_name %in% c("Loan originated", "Application approved but not accepted"), "Y", "N"))

```

```{r}
# Race
ggplot(loan, aes(x = applicant_race_name_1)) +
  geom_bar(aes(fill = approved)) +
  labs(x = "Race", y = "Count", title = "Distribution of Loan Approval by Race",
       fill = " Loan Originated") + 
  theme(axis.text.x =element_text(angle = 10)) + 
  project_theme

# Sex
ggplot(loan, aes(x = applicant_sex_name)) +
  geom_bar(aes(fill = approved)) +
  labs(x = "Sex", y = "Count", title = "Distribution of Loan Approval by Sex",
       fill = " Loan Originated") + 
  project_theme

# State
ggplot(loan, aes(x =state_abbr)) +
  geom_bar(aes(fill = approved)) +
  labs(x = "State of Loan Request",
       y = "Count",
       title = "Distribution of Loan Approval by State",
       fill = " Loan Originated") + 
  theme(axis.text.x =element_text(angle = 90, hjust = 1)) + 
  project_theme

# co-applicant

ggplot(loan, aes(x = approved)) +
  geom_bar(aes(fill = co_applicant_race_name_1)) +
  labs(x = "Co-Applicant Race",
       y = "Count",
       title = "Distribution of Loan Approval by State",
       fill = " Loan Originated") + 
  theme(axis.text.x =element_text(angle = 90, hjust = 1)) + 
  project_theme
```


```{r}

# income histogram

ggplot(filter(loan, applicant_income_000s < 2000), aes(applicant_income_000s)) +
  geom_histogram(binwidth = 50) + 
  labs(x = "Income (Thousands)",
       y = "", 
       title = "Distribution of Applicant Income") +
  project_theme

# obs left out of graph
loan %>% filter(applicant_income_000s >= 2000) %>% nrow()


```


```{r}

# loan amount requested distribution
ggplot(filter(loan, loan_amount_000s < 2000), aes(loan_amount_000s)) +
  geom_histogram(binwidth = 50) + 
  labs(x = "Loan Amount (Thousands)",
       y = "", 
       title = "Distribution of Loan amount requested") +
  project_theme

# obs left out of graph
loan %>% filter(loan_amount_000s >= 2000) %>% nrow()

```



```{r}

library(stringr)
# Applicant income by race boxplot
ggplot(filter(loan, applicant_income_000s < 500), aes(x = applicant_race_name_1, y = applicant_income_000s)) +
  geom_boxplot() +
  labs(x = "Applicant Race",
       y = "Applicant Income (Thousands)",
       title = "Distribution of Applicant Income by Race") +
  project_theme +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 20))

# obs left out of the graph
loan %>% filter(applicant_income_000s >= 500) %>% nrow()
```


```{r}

# Applicant income by race boxplot
ggplot(filter(loan, loan_amount_000s < 1000), aes(x = applicant_race_name_1, y = loan_amount_000s)) +
  geom_boxplot() +
  labs(x = "Applicant Race",
       y = "Applicant Loan Amount (Thousands)",
       title = "Distribution of Applicant Income by Race") +
  project_theme +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 20))

# obs left out of graph
loan %>% filter(loan_amount_000s >= 1000) %>% nrow()

```


```{r}
## 75% of the sample size
smp_size <- floor(0.75 * nrow(loan))

## set the seed to make your partition reproducible
set.seed(42)
train_ind <- sample(seq_len(nrow(loan)), size = smp_size)
class(loan)
train <- loan[train_ind,]
test <- loan[-train_ind,]
class(train)
# Create train dataset
write.csv(train, file = "train.csv")


# Create test dataset
write.csv(test, file = "test.csv")

```
